### ISSUE TITLE
testing problem

### ISSUE THREAD

**Issue by jzhe3** [NCAR/iCESM1.2#8]
Hello,i learn to setup a CESM simulation with water isotopes(use icesm1.2) referring to your tutorial(water_isotope_instructions.txt and water_tag_instructions.txt), but I got an error after running it((use *.submit).  The error result is as follows：
![image](https://user-images.githubusercontent.com/37427804/113416534-24954e00-93f4-11eb-9d4b-d5ef6057ad54.png)

[erorrs.zip](https://github.com/NCAR/iCESM1.2/files/6249542/erorrs.zip)
so , could you tell me where is the problem?

**Comment by nusbaume** [comment]
Hi @tomorrgod, it looks like your `finidat` file doesn't contain any isotope fields.  You can fix this by using the NCL script and associated netcdf files present here:

https://github.com/NCAR/iCESM1.2/tree/master/instructions/water_isotopes

to add the relevant water isotope fields to the specific `finidat` file being used in your run. 

Also, Github issues are mainly used to manage software bugs for this repo.  For general problems in getting the model working it would be better to create a post on the DiscussCESM forums first, with the best fit likely being the Paleoclimate forum:

https://bb.cgd.ucar.edu/cesm/forums/paleoclimate.139/

If afterwards it is found that there is a real bug then an issue will be created for you. Thus I am going to go-ahead and close this issue, but please create a forum post if you need additional help.

Thanks, and have a great day!

**Comment by jzhe3** [comment]
thanks
